stages:
  - build
  - build_image

# 引入镜像构建相关的任务

variables:
  BUILD_ARTIFACTS_PATH: "output"
  BUILD_DIR: "dist"
  CI: "false"

build:
  stage: build
  image: node:12.16
  retry: 2
  before_script:
    - yarn config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - yarn config set phantomjs_cdnurl https://npm.taobao.org/mirrors/phantomjs/
    - yarn config set electron_mirror https://npm.taobao.org/mirrors/electron/
    - yarn config set registry https://npm.ascs.tech/
  script:
    - yarn 
    - yarn build
    - mkdir $BUILD_ARTIFACTS_PATH
    - cp -r ${BUILD_DIR} $BUILD_ARTIFACTS_PATH/dist
    - cp docker-entrypoint.sh $BUILD_ARTIFACTS_PATH
    - cp Dockerfile $BUILD_ARTIFACTS_PATH
  artifacts:
    when: on_success
    paths:
      - ${BUILD_ARTIFACTS_PATH}/*
    name: ${CI_PROJECT_NAME}
  cache:
    key: build_cache
    paths:
      - node_module
    policy: pull-push
  only:
    - tags
    - master
    - develop
    - /^release\/\d+\.\d+\.\d+$/
    - merge_requests
    - web
include:
  project: "ci/ci-template"
  file: "build_image.yml"
  ref: master
